#!/bin/sh

# Replaces the default gnome theme
rm /usr/share/gnome-shell/gnome-shell-theme.gresource
cp /usr/share/gnome-shell/big-gnome-shell-theme.gresource  /usr/share/gnome-shell/gnome-shell-theme.gresource

