# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

## arg 1:  the new package version
post_install() {
	# Execute the big-gdm-greeter script
	bash /usr/share/libalpm/scripts/big-gdm-greeter
	
	# Desativar a montagem automática de dispositivos
	gsettings set org.gnome.desktop.media-handling automount false
}

## arg 2:  the old package version
post_upgrade() {
	post_install
}
